[build]
target = ["x86_64-unknown-linux-gnu", "aarch64-linux-android", "x86_64-pc-windows-gnu"]

[target.aarch64-linux-android]
ar = "/home/kelvin/Android/Sdk/Ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
linker = "/home/kelvin/Android/Sdk/Ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-clang"
